################################################################################
# File:     Makefile
# Author:   GAndaLF
# Brief:    Makefile script containing all hw test targets.
################################################################################

all : \
template \

clean : \
template_clean \

################################################################################
# Template HW test target

template :
	@make -C template -f conf.mk

template_clean :
	@make -C template -f conf.mk clean

#
################################################################################

################################################################################
# HW test targets

#
################################################################################

.PHONY: all clean

.PHONY: template template_clean